main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: ASoftGlow
description: DESCRIPTION
depend: ["GuiLib", "FastAsyncWorldEdit"]
commands:
  class:
    description: Opens class switcher
    permission: admin.manage.serverpermission
  zvh:
    description: Base command for ZvH
    permission: admin.manage.serverpermission
  leave:
    aliases: l
    description: Exits the arena
  resetmap:
    permission: admin.manage.serverpermission
  shop:
    aliases: s
    description: Opens the shop while in-game
  die:
    aliases: kablooey
    description: makes you die
  music:
    description: Base command to control music
  join:
    aliases: j
    description: Join the current game, if one is running, otherwise join the queue
  guide:
    description: Opens the guide book
  mute:
    permission: admin.manage.serverpermission
  unmute:
    permission: admin.manage.serverpermission
  mutelist:
    permission: admin.manage.serverpermission
  reload-config:
    permission: admin.manage.serverpermission
  rules:
  discord:
  stats:
    description: Display in-game stats about a player
  cosmetics:
    desription: Customize your in-game cosmetics