main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: ASoftGlow
description: DESCRIPTION
depend: ["GuiLib", "FastAsyncWorldEdit"]
commands:
  class:
    description: Opens class switcher
  zvh:
    description: Base command for ZvH
    permission: admin.manage.serverpermission
  leave:
    aliases: l
    description: Exits the arena
  resetmap:
    description: idk
    permission: admin.manage.serverpermission
  afk:
    description: Sends an afk notification to everyone
    permission: admin.manage.serverpermission
  shop:
    description: Opens the shop while in-game

permissions:
  example.test:
    description: DESCRIPTION
    default: true
  example.*:
    description: Grants all other permissions
    default: false
    children:
      example.test: true